blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/researchaccelerator-hub/princeton-smart/discussions/categories/ideas
    about: Suggest a new feature or capability for SMART
  - name: Questions / General Discussion
    url: https://github.com/researchaccelerator-hub/princeton-smart/discussions
    about: Ask a question or start a general discussion
