package com.screenlake.recorder.constants

object ConstantSettings {
    const val IS_PRODUCTION = true
    const val PERMISSIONS_REQUEST_CODE = 0
    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_START_MANUAL_UPLOAD = "ACTION_START_MANUAL_UPLOAD"
    const val ACTION_SHOW_RECORDING_FRAGMENT = "ACTION_SHOW_RECORDING_FRAGMENT"
    const val ACTION_SHOW_RECORDING_FRAGMENT_IMM_RECORD = "ACTION_SHOW_RECORDING_FRAGMENT_IMM_RECORD"
    const val RECORDING_SERVICE = "RECORDING_SERVICE"
    const val LOGGED_OUT = "LOGGED_OUT"
    const val UPLOAD_FAILED = "UPLOAD_FAILED"
    const val COROUTINE_EXCEPTION_HANDLER = "COROUTINE_EXCEPTION_HANDLER"
    const val IS_CONNECTED = "IS_CONNECTED"
    const val IS_RECORDING = "IS_RECORDING"
    const val IS_POWERED = "IS_POWERED"
    const val OCR_NOT = "OCR_NOT"
    const val OCR_DONE = "OCR_DONE"
    const val RECORD_TRIGGERED = "RECORD_TRIGGERED"
    const val ZIPPING = "ZIPPING"
    const val RE_ENABLE_NOTIFICATION = "RE_ENABLE_NOTIFICATION"
    const val OUT_OF_MEMORY = "OUT_OF_MEMORY"
    const val SERVICE_STOP = "SERVICE_STOP"
    const val SAFE_LAUNCH_CANCELLATION = "SAFE_LAUNCH_CANCELLATION"
    const val SAFE_LAUNCH = "SERVICE_STOP"


    val SCREENSHOT_MAPPING = mutableMapOf(
        0.1 to 10000L,
        0.2 to 5000L,
        0.3 to 3000L,
        0.4 to 2500L,
        0.5 to 2000L,
        1.0 to 1000L,
        2.0 to 500L,
        3.0 to 333L,
        4.0 to 250L,
        5.0 to 200L,
        10.0 to 100L,
        20.0 to 50L,
        30.0 to 33L
    )
    const val SCREENSHOT_IMAGE_QUALITY = 50

    const val NOTIFICATION_CHANNEL_ID = "recording_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Tracking"

    // Test values.
    private const val DEBUG_BATCH_SIZE = 5
    private const val DEBUG_METRIC_INTERVAL = 9000L
    private const val DEBUG_CHECK_CREDENTIAL = 10800000
    private const val DEBUG_PERCENT_USED_LIMIT = 95.0

    // TODO: Rethink these intervals
    // Do not change!
    private const val BATCH_SIZE = 10
    private const val METRIC_INTERVAL = 360000L
    private const val CHECK_CREDENTIAL = 10800000
    private const val PERCENT_USED_LIMIT = 95.0

    fun getPercentUsedLimitInterval() : Double {
        return if(isDebug()){
            DEBUG_PERCENT_USED_LIMIT
        }else{
            PERCENT_USED_LIMIT
        }
    }

    fun getBatch(testing: Boolean = false) : Int {
        return if(testing){
            1
        }else if(isDebug()){
            DEBUG_BATCH_SIZE
        }else{
            BATCH_SIZE
        }
    }

    fun getMetricInterval() : Long {
        return if(isDebug()){
            DEBUG_METRIC_INTERVAL
        }else{
            METRIC_INTERVAL
        }
    }

    fun getCredentialInterval() : Int {
        return if(isDebug()){
            DEBUG_CHECK_CREDENTIAL
        }else{
            CHECK_CREDENTIAL
        }
    }

    //    private fun isDebug() = BuildConfig.DEBUG&& BuildConfig.BUILD_TYPE == "debug"
    private fun isDebug() = true

    val RESTRICTED_APPS = mutableListOf(
        "com.sec.android.app.launcher",
        "com.android.settings",
        "com.screenlake",
        "com.google.android.apps.nexuslauncher",
        "com.lab465.SmoreApp",
        "ae.primehealth",
        "ai.abridge.nativeclient.release",
        "ai.kanghealth",
        "app.com.chefaa",
        "app.indie.my",
        "app.medicalid.free",
        "atws.app",
        "au.gov.dhs.expressplus.medicare",
        "bokf.ib.android.market.abq",
        "bokf.ib.android.market.bot",
        "br.com.gabba.Caixa",
        "br.gov.dataprev.meuinss",
        "co.ibex.almeezan",
        "co.uk.getmondo",
        "com.abcbs.ark_blue_cross",
        "com.acorns.android",
        "com.ada.app",
        "com.adcb.bank",
        "com.adcb.cbgdigi",
        "com.ADCBApp.ADCBOffers",
        "com.adp.wiselymobile",
        "com.adpmobile.android",
        "com.aetna.aetnabetterhealthmobile",
        "com.afcu.mobilebanking",
        "com.ahatpa.ahamobile",
        "com.allstate.view",
        "com.ally.MobileBanking",
        "com.amazon.phseven.prod",
        "com.americanexpress.android.acctsvcs.us",
        "com.americanwell.android.member.amwell",
        "com.americanwell.android.member.optum",
        "com.americanwell.android.member.wellpoint",
        "com.americaspharmacy.app",
        "com.amfam.myamfam",
        "com.amfam.myamfam",
        "com.anthem.employer.prod",
        "com.anthem.mobile.broker.plus",
        "com.anthem.pulse",
        "com.anthem.sydney",
        "com.anytimepediatric.anytimetelemedicine",
        "com.ar.mdp",
        "com.arabbank.neobank",
        "com.aranoah.healthkart.plus",
        "com.arvest.arvestgo",
        "com.aspiration.app",
        "com.athenahealth.athenapatient",
        "com.avant.android.app",
        "com.avanza.ambitwizfbl",
        "com.aventri.cignameetings300014317",
        "com.axiscare",
        "com.babycenter.pregnancytracker",
        "com.ballad.bha",
        "com.bancodeguayaquil",
        "com.bank.danamon",
        "com.bankofamerica.prepaid",
        "com.bankofamerica.wmyhealth",
        "com.bannerhealth.BannerHealthMobileApp",
        "com.barclaycardus",
        "com.bcbsfepdentalmemberapp",
        "com.bcbsm.mmaprod",
        "com.bcbssc.myhealthtoolkit.mobile",
        "com.betterhelp",
        "com.betterment",
        "com.binance.dev",
        "com.biocyte.safe",
        "com.bloomapi.bloomtext",
        "com.bluebird.mobile",
        "com.blueshieldca.prod",
        "com.bm.android.thermometer",
        "com.bmoharris.digital",
        "com.bnft.solutran",
        "com.bob.umr",
        "com.botw.mobilebanking",
        "com.brightcapital.app",
        "com.bwh.android",
        "com.calmerry.client.app",
        "com.capitalone.credittracker",
        "com.cardinalcommerce.greendot",
        "com.careatc.patientportal",
        "com.caremark.caremark",
        "com.caremarket.communitycareexplorer.prod",
        "com.castlight.clh.view",
        "com.centene.hnet",
        "com.centene.iatotalcare",
        "com.centene.myLHCC",
        "com.centene.sunshine",
        "com.cerner.iris.play",
        "com.chase.intl",
        "com.chase.sig.android",
        "com.cigna.mobile.envoy",
        "com.cigna.mobile.mycigna",
        "com.cigna.mobile.wellbeing",
        "com.cignahealthbenefits.mobileapp",
        "com.cirrusmd.h2h.android",
        "com.cirrusmd.uhc.android",
        "com.cirrusmd.vahealthchat",
        "com.citi.citimobile",
        "com.citizensbank.androidapp",
        "com.clairmail.fth",
        "com.clue.android",
        "com.coindcx.btc",
        "com.coloradostate.health",
        "com.creditkarma.mobile",
        "com.creditonebank.mobile",
        "com.cu1.cu1",
        "com.current.app",
        "com.cvs.launchers.cvs",
        "com.dartmouthhitchcock.android",
        "com.dave",
        "com.ddpa.mobileapp",
        "com.dentaquest.mydentaquest",
        "com.devexperts.tdmobile.platform.android.thinkorswim",
        "com.digitalpharmacist.cardinal",
        "com.discoverfinancial.mobile",
        "com.doctorondemand.android.patient",
        "com.dreamplug.androidapp",
        "com.eahli.ABKEG",
        "com.easymobs.pregnancy",
        "com.ecw.emobile",
        "com.ecw.healow",
        "com.ecw.healowkids",
        "com.elan.icsmobile.elanapp",
        "com.encryptscan.encryptscan_android",
        "com.enlythealth.mercyhealthpatient.android",
        "com.essence.welinq",
        "com.etrade.mobilepro.activity",
        "com.experian.android",
        "com.firstbank.mobilebanking",
        "com.firstpremier.mypremiercreditcard.app",
        "com.firstrepublic.banking",
        "com.flmedicaid.smmcmemberportal",
        "com.flowhealth.mp_android.patient",
        "com.fredsmeds.rx",
        "com.froedtert.care",
        "com.fruth.android",
        "com.galileohealth.android",
        "com.getheal.patient",
        "com.glic.group.ga.mobile",
        "com.glow.android.eve",
        "com.glow.android.nurture",
        "com.gobank",
        "com.golden1.mobilebanking",
        "com.goodrx",
        "com.google.android.apps.healthdata",
        "com.google.android.apps.walletnfcrel",
        "com.greendotcorp.go2bank",
        "com.hcahealthcare.mhom",
        "com.hcsc.android.providerfinderil",
        "com.hcsc.android.providerfindertx",
        "com.health.insurance.app.online",
        "com.healthtap.userhtexpress",
        "com.healthtrioconnect.avera",
        "com.henryford.android",
        "com.hingehealth.phoenix",
        "com.hioscar.member",
        "com.hp.pregnancy.lite",
        "com.hrblock.AtHome",
        "com.hrblock.blockmobile",
        "com.hucu.ai",
        "com.humana.myhumana",
        "com.humana.pharmacy",
        "com.idfcfirstbank.optimus",
        "com.ifeel.ifeeluserchat",
        "com.ifs.banking.fiid1532",
        "com.ifs.banking.fiid7001",
        "com.infonow.bofa",
        "com.ingles.rx",
        "com.insiderx.mobile",
        "com.intuit.mobile.taxcaster",
        "com.intuit.qbse",
        "com.intuit.turbotax.mobile",
        "com.investroo.zoya",
        "com.jardogs.fmhmobile",
        "com.jpm.sig.android",
        "com.key.android",
        "com.konylabs.capitalone",
        "com.ladytimer.ovulationcalendar",
        "com.laser2mail.uhcsrmobile",
        "com.lbrc.PeriodCalendar",
        "com.leftbraingames.SecureMyMedRecords",
        "com.lemonadeinc.lemonade",
        "com.lexi.android",
        "com.lfg.consumerparticipant.dental",
        "com.libertydentalplan.mobile",
        "com.libertytax.libertytaxmobile",
        "com.lowestmed.android",
        "com.lsdinfotech.medicationlist",
        "com.lybrate.phoenix",
        "com.marcus.android",
        "com.marylandhealthconnection.mobile",
        "com.maxi.wasfa",
        "com.maximus.enrollment.healthyla",
        "com.maximus.enrollment.nc",
        "com.maximus.pa_enrollment_services",
        "com.mayoclinic.patient",
        "com.mcom.firstcitizens",
        "com.mdaware.mdcalc",
        "com.medco.medcopharmacy",
        "com.medex.yodawy",
        "com.medicarecenter",
        "com.mediconnect.oladoc",
        "com.medisafe.android.client",
        "com.meditech.PatientPhm",
        "com.medmutual.mhp",
        "com.medpresso.Lonestar.jhuobgyn",
        "com.medscape.android",
        "com.meetalbert",
        "com.meetyou.intl",
        "com.mercury.bank",
        "com.mfoundry.mb.android.mb_104",
        "com.mfoundry.mb.android.mb_zfnb_pb",
        "com.mint",
        "com.ml.mobile.edge",
        "com.ml.mobile.mymerrill",
        "com.mobile.uhc",
        "com.modernizingmedicine.patientportal",
        "com.mohitatray.prescriptionmaker",
        "com.molina.mobile.myhealthinhand",
        "com.moodtools.cbtassistant.app",
        "com.mycareplan.ppgwni.careplan",
        "com.mycareplan.ppmycare.careplan",
        "com.myfico",
        "com.mymhealth.hybrid",
        "com.myquest",
        "com.naturalcycles.cordova",
        "com.navyfederal.android",
        "com.nebraska.rx",
        "com.netspend.product.android.ace",
        "com.newtechsys.rxlocalmobile",
        "com.nextcare.health",
        "com.nm.nm",
        "com.nu.production",
        "com.nupuit.life",
        "com.nv1.mdp",
        "com.onedebit.chime",
        "com.onefinance.one",
        "com.onemedical.android",
        "com.optavia",
        "com.optum.rx",
        "com.osellus.android.pineapp",
        "com.ovuline.fertility",
        "com.ovuline.pregnancy",
        "com.pearlii",
        "com.period.tracker.lite",
        "com.periodtracker.periodcalendar.ovulation.periodcycle",
        "com.pgac.general.droid",
        "com.pharmacyadvantage.android",
        "com.phonegap.rxpal",
        "com.phonevalley.progressive",
        "com.plushcare.plushcare.prod",
        "com.plutus.wallet",
        "com.pnc.ecommerce.mobile",
        "com.policybazaar",
        "com.popularapp.periodcalendar",
        "com.ppfa.direct",
        "com.practo.droid",
        "com.practo.fabric",
        "com.premera.android",
        "com.pristyncare.patientapp",
        "com.propel.ebenefits",
        "com.publix.pharmacyonline",
        "com.q2e.texasdowcreditunion5004401st.mobile.production",
        "com.qualbe1dapp.android",
        "com.quantumx.mydental",
        "com.quartertone.medcalc.obwheel",
        "com.ramp.android.app",
        "com.rbc.mobile.android",
        "com.regence.regenceapp",
        "com.resmed.airmini",
        "com.resmed.myair",
        "com.rhinonative",
        "com.riteaid.android",
        "com.rxgo",
        "com.rxr.production",
        "com.sbi.lotusintouch",
        "com.schwab.mobile",
        "com.schwab.mobile.retirement",
        "com.sequoia.android",
        "com.simplepractice.simple",
        "com.simplepractice.video",
        "com.singlecare.scma",
        "com.smsrobot.period",
        "com.snap.connectedcare.hometownProduction",
        "com.sofi.mobile",
        "com.softek.ofxclmobile.macu",
        "com.soln.SE35BCA74A3BE95A854E67E90FEB1DBB3",
        "com.solutran.healthysavings",
        "com.solutran.otc",
        "com.sovereign.santander",
        "com.spruce.messenger",
        "com.spruce.messenger",
        "com.stanfordchildrens.LPCH_Connect",
        "com.statefarm.pocketagent",
        "com.subsplashconsulting.s_BZ72MF",
        "com.ta.mhav",
        "com.talkspace.talkspaceapp",
        "com.taxact.express2013",
        "com.taxslayerRFC",
        "com.tch.mychart",
        "com.tdameritrade.mobile3",
        "com.tdbank",
        "com.teladoc.members",
        "com.tigertext",
        "com.truist.mobile",
        "com.tufts.mobilemember",
        "com.uba.vericash",
        "com.ucci.dmw",
        "com.uhg.mobile.lean",
        "com.uhg.mobile.uhcglobal",
        "com.unionbankph.corporate",
        "com.unionbankph.online",
        "com.unitedhealthgroup",
        "com.upmc.enterprises.myupmc",
        "com.upmc.healthplan",
        "com.usaa.mobile.android.usaa",
        "com.usbank.mobilebanking",
        "com.ustrust.mobileapps.accountaccessandroid",
        "com.va.wholehealth",
        "com.varomoney.bank",
        "com.vellhealth.apps.vellhealth",
        "com.verifly.smb",
        "com.villagemd.patx",
        "com.vivahealth.app",
        "com.wachanga.womancalendar",
        "com.wahed.mobile",
        "com.wave.personal",
        "com.webmd.android",
        "com.wellforce.hip",
        "com.wellsFargo.ceomobile",
        "com.wf.wellsfargomobile",
        "com.winndixie.rx.android",
        "com.woodforest",
        "com.workday.workdroidapp",
        "com.yml.frbcorpandroid",
        "com.zocdoc.android",
        "digit.android",
        "edu.northwell.dpxapp",
        "edu.osumc.healthassistant.app",
        "epic.mychart.android",
        "Fi_Mobile.Dupaco",
        "fr.doctolib.www",
        "gentlebirth.app",
        "gov.irs",
        "gov.medicare.coverage",
        "gov.va.mobileapp",
        "gov.va.smhd",
        "gov.va.vamf.vavideoconnect",
        "in.plackal.lovecyclesfree",
        "invo8.meezan.mb",
        "is.vertical.ptsdcoach",
        "lili.co",
        "me.greenlight",
        "net.bac.sbe.android",
        "net.gtl.mobile_app",
        "org.ascension.ascensionrx",
        "org.ascension.memberexperience",
        "org.becu.androidapp",
        "org.carolinas.android.dir",
        "org.ccf.patientapp",
        "org.chsli.catholichealth",
        "org.cookchildrens.mychart",
        "org.dignityhealth.appdev.myhome",
        "org.dignityhealth.healthelife.chw_ca.play",
        "org.dukehealth.mydukehealthapp",
        "org.fairview.mychart",
        "org.hesperian.Safe_Abortion",
        "org.houstonmethodist.methodistmobile",
        "org.iggymedia.periodtracker",
        "org.ihc.dfd",
        "org.jacksonhealth.myjacksonhealth.play",
        "org.kp.m",
        "org.mountsinai.MyChart",
        "org.mountsinai.MyChart",
        "org.nm.mobile.myNM",
        "org.nm.nmconnect",
        "org.northshore.northshoreconnect",
        "org.nyp.nyppatient.android",
        "org.nyulmc.clinical.mychart",
        "org.partners.bwhresearchapp.asthma20",
        "org.partners.ondemandvideouc",
        "org.partners.ppgmob",
        "org.penfed.mobile.banking",
        "org.redeemerfcu.MobileBanking",
        "org.schoolsfirstfcu.mobile.banking.isam",
        "org.spectrum_health.mySpectrum",
        "org.stanfordhealthcare.myhealth",
        "org.suncoast.mobile",
        "org.sutterhealth.myhealthonline",
        "org.temple.health",
        "org.TexasHealth.TexasHealthMyChart",
        "org.trinity.health",
        "org.trinityhealth.trinityhealth",
        "org.uhhospitals.mychart",
        "org.uwcu.app.mobile",
        "org.wescom.ibranch",
        "org.womenonwaves.app",
        "org.wsecu.n",
        "periodtracker.pregnancy.ovulationtracker",
        "premom.eh.com.ehpremomapp",
        "providence.nassau.mobile.providencehealth",
        "raj.rohit.android.Form1040EZ",
        "ru.mobiledimension.kbr",
        "shop.shop_apotheke.com.shopapotheke",
        "sone.mbanking",
        "us.hsbc.hsbcus",
        "us.tx.state.hhsc.ytbmobile",
        "wibmo.com.wibmoAuthApp",
        "world.thoughtfull.user",
        "xyz.rtrvr.pillo",
        "zapsolutions.strike")
}